notifications:
  email: false
sudo: required
language: generic

services:
  - docker

script:
  - sh travis/script.sh

branches:
  except:
    - /^debian\/\d/

deploy:
  provider: releases
  api_key: "${GH_OAUTH_TOKEN}"
  skip_cleanup: true
  file_glob: true
  file: "*.deb"
  overwrite: true
  on:
    tags: true
